[package]
name = "kproxy"
version = "0.1.0"
edition = "2021"


[dependencies]
cliparser = "0.1.2"
lazy_static = "1.5.0"
libc = "0.2.155"
mio = {version = "1.0.0", features = ['net','log','os-poll','os-ext']}
